##INGRESS SHARDING ICIN ORNEKTIR.

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: dev-ingress
  namespace: openshift-ingress-operator
spec:
  domain: dev.ocp.example.local
  replicas: 3
  endpointPublishingStrategy:
    type: HostNetwork   # Orjinal ingresscontrollerdan teyid edilebilir.
    hostNetwork:
      httpPort: 8081
      httpsPort: 8443
      statsPort: 1937
      protocol: TCP
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:                   # Orjinal ingresscontrollerdan teyid edilebilir.
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  namespaceSelector:
    matchLabels:
      env: dev  ## ETIKETE DIKKAT
